In [1]:
import pandas as pd
df = pd.read_csv("MOCK_DATA.csv")

In [2]:
df.head()

   id  group               name  age               city  score
0   1  Gamma          Lonna Esp    1              Örgön    9.0
1   2  Delta     Harmonia Malek    2           Rajadesa   33.0
2   3  Delta      Jammal Wigley    3               Sobo   65.0
3   4   Beta    Tomasina Hedger    4          Podgórzyn   75.0
4   5  Gamma  Boycey Balhatchet    5  Moravská Nová Ves   42.0

In [3]:
df.head(10)

   id  group                 name  age                  city  score
0   1  Gamma            Lonna Esp    1                 Örgön    9.0
1   2  Delta       Harmonia Malek    2              Rajadesa   33.0
2   3  Delta        Jammal Wigley    3                  Sobo   65.0
3   4   Beta      Tomasina Hedger    4             Podgórzyn   75.0
4   5  Gamma    Boycey Balhatchet    5     Moravská Nová Ves   42.0
5   6   Beta         Agnese Isgar    6             Jingchuan   70.0
6   7  Gamma          Reg MacLaig    7      Qiziltepa Shahri   97.0
7   8   Beta        Hermia Atrill    8  Carrazeda de Ansiães   39.0
8   9  Alpha  Granthem Mottinelli    9                Jeleuk   99.0
9  10   Beta        Lucas Zebedee   10           Ikalamavony   73.0

In [4]:
df.dtypes

id         int64
group        str
name         str
age        int64
city         str
score    float64
dtype: object

In [5]:
df["group"].unique()

<StringArray>
['Gamma', 'Delta', 'Beta', 'Alpha', nan]
Length: 5, dtype: str